### ISSUE TITLE
 Invalid registration attempt for an Ore Dictionary item with name blockVoid

### ISSUE THREAD

**Issue by BunnyCinnamon** [BluSunrize/WitchingGadgets#108]
Is this bad?

[11:20:29] [Client thread/TRACE] [WitchingGadgets/WitchingGadgets]: Sending event FMLPreInitializationEvent to mod WitchingGadgets
[11:20:29] [Client thread/INFO] [WitchingGadgets/WitchingGadgets]: Setting up 'WitchingGadgets'
[11:20:29] [Client thread/WARN] [FML/WitchingGadgets]: ****************************************
[11:20:29] [Client thread/WARN] [FML/WitchingGadgets]: \* Invalid registration attempt for an Ore Dictionary item with name blockVoid has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
[11:20:29] [Client thread/WARN] [FML/WitchingGadgets]: \*  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:491)
[11:20:29] [Client thread/WARN] [FML/WitchingGadgets]: \*  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:470)
[11:20:29] [Client thread/WARN] [FML/WitchingGadgets]: \*  at witchinggadgets.common.WGContent.preInitItems(WGContent.java:346)
[11:20:29] [Client thread/WARN] [FML/WitchingGadgets]: \*  at witchinggadgets.common.WGContent.preInit(WGContent.java:156)
[11:20:29] [Client thread/WARN] [FML/WitchingGadgets]: \*  at witchinggadgets.WitchingGadgets.preInit(WitchingGadgets.java:70)
[11:20:29] [Client thread/WARN] [FML/WitchingGadgets]: \*  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
[11:20:29] [Client thread/WARN] [FML/WitchingGadgets]: ****************************************
[11:20:29] [Client thread/TRACE] [WitchingGadgets/WitchingGadgets]: Sent event FMLPreInitializationEvent to mod WitchingGadgets

**Comment by BluSunrize** [comment]
It's a bit undesireable but nothing gamebreaking or endangering. Nothing else but WG uses blockVoid, so no worries.

**Comment by Mordenkainen** [comment]
This can easily be fixed by removing the following line on your next bug fix cycle:

https://github.com/BluSunrize/WitchingGadgets/blob/master/src/main/java/witchinggadgets/common/WGContent.java#L346

You are already registering this oreDict when you register your blocks.
