### ISSUE TITLE
wolven cloak crashes in the presence of health-removing debuffs

### ISSUE THREAD

**Issue by Azutte** [BluSunrize/WitchingGadgets#16]
Noticed it from Automagy's vishroom soup, which poisons you in addition to other things. Thought it was on their end, but then I got the same crash while fighting some wither skeletons.

**Comment by Azutte** [comment]
Ooops! Crashlog:

---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 3/12/15 6:26 PM
Description: Ticking player

java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
    at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
    at net.minecraft.entity.EntityLivingBase.func_70679_bo(EntityLivingBase.java:521)
    at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:293)
    at net.minecraft.entity.Entity.func_70071_h_(Entity.java:318)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1561)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295)
    at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
    at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
    at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:8)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
    at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
    at net.minecraft.entity.EntityLivingBase.func_70679_bo(EntityLivingBase.java:521)
    at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:293)
    at net.minecraft.entity.Entity.func_70071_h_(Entity.java:318)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1561)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)

-- Player being ticked --
Details:
    Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
    Entity ID: 333
    Entity Name: Azumarill
    Entity's Exact location: 28.12, 60.00, -94.54
    Entity's Block location: World: (28,60,-95), Chunk: (at 12,3,1 in 1,-6; contains blocks 16,0,-96 to 31,255,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295)
    at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
    at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
    at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:8)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
    Connection: net.minecraft.network.NetworkManager@172faad
Stacktrace:
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by BluSunrize** [comment]
Hmm, I've actually experienced that error before myself. I might have found a fixed for it though. It will be in the next version.

**Comment by EXTER7** [comment]
This issue still happens in 1.1.6

Crash report:
http://pastebin.com/BAis5ukb

It usually happens when I get wither or poison.

**Comment by BluSunrize** [comment]
I need details on your equipment.

**Comment by EXTER7** [comment]
Here the equipment i have:
- Armor:
  - Elementium Helmet of Revealing (Botania)
  - Elementium Chestplate (Botania)
  - Elementium Leggings (Botania)
  - Elementium Boots (Botania)
- Baubles:
  - Crimson Pendant (Botania)
  - Charged Ring of Shielding (Thaumcraft)
  - Ring of Nutrition (Forbidden Magic)
  - Girdle of Runic Shielding (Thaumcraft)
- Traveller's Gear:
  - Steadfast Spaulders (Witching Gadgets)
  - Berserker's Bracers (Witching Gadgets)
  - Wolven Cloak (Witching Gadgets)
  - Title: Crimson Cult (Witching Gadgets)
