### ISSUE TITLE
Random crash with this and the multiplecamera mod

### ISSUE THREAD

**Issue by crunkazcanbe** [BluSunrize/WitchingGadgets#21]
Multiple camera is a Japanese mod that adds surveillance cameras that actually work .

It worked until i installed this mod , and I have 340 mods in my mod pack .

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 3/21/15 3:30 AM
Description: Unexpected error

java.lang.ClassCastException: noki.multiplecamera.camera.EntityCamera cannot be cast to net.minecraft.entity.player.EntityPlayer
    at witchinggadgets.client.ClientTickHandler.renderTick(ClientTickHandler.java:27)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_1789_ClientTickHandler_renderTick_RenderTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at cpw.mods.fml.common.FMLCommonHandler.onRenderTickStart(FMLCommonHandler.java:335)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:987)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
    at org.multimc.EntryPoint.listen(EntryPoint.java:165)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at witchinggadgets.client.ClientTickHandler.renderTick(ClientTickHandler.java:27)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_1789_ClientTickHandler_renderTick_RenderTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)

**Comment by BluSunrize** [comment]
Will be fixed in the next version, thanks for the report

**Comment by crunkazcanbe** [comment]
Thank you man!
