### ISSUE TITLE
Infinite recursion crash

### ISSUE THREAD

**Issue by Belgabor** [BluSunrize/WitchingGadgets#54]
We have an infinite recursion crash on our server when a player shift-right clicked a brain in a jar next to a spawner (amnesic stone from autamagy below it, hence the shift clicking). She had the Stealth enchantment on her armor, which, if I read the code right, is probably part of the cause.

Server Log:

```
[16:21:03] [Server thread/ERROR] [FML/]: Index: 1 Listeners:
[16:21:03] [Server thread/ERROR] [FML/]: 0: NORMAL
[16:21:03] [Server thread/ERROR] [FML/]: 1: ASM: witchinggadgets.common.util.handler.EventHandler@3e3fc7f9 onLivingSetTarget(Lnet/minecraftforge/event/entity/living/LivingSetAttackTargetEvent;)V
[16:21:03] [Server thread/ERROR] [FML/]: 2: ASM: travellersgear.common.util.TGEventHandler@73e555b0 onPlayerTargeted(Lnet/minecraftforge/event/entity/living/LivingSetAttackTargetEvent;)V
[16:21:03] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.entity.living.LivingSetAttackTargetEvent@7ec993d9:
java.lang.StackOverflowError
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_67]
    at java.lang.ClassLoader.checkPackageAccess(ClassLoader.java:501) ~[?:1.7.0_67]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:144) ~[EventBus.class:?]
    at net.minecraftforge.common.ForgeHooks.onLivingSetAttackTarget(ForgeHooks.java:282) ~[ForgeHooks.class:?]
    at net.minecraft.entity.EntityLiving.func_70624_b(EntityLiving.java:123) ~[sw.class:?]
    at witchinggadgets.common.util.handler.EventHandler.onLivingSetTarget(EventHandler.java:132) ~[EventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_239_EventHandler_onLivingSetTarget_LivingSetAttackTargetEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
    at net.minecraftforge.common.ForgeHooks.onLivingSetAttackTarget(ForgeHooks.java:282) ~[ForgeHooks.class:?]
    at net.minecraft.entity.EntityLiving.func_70624_b(EntityLiving.java:123) ~[sw.class:?]
    at witchinggadgets.common.util.handler.EventHandler.onLivingSetTarget(EventHandler.java:132) ~[EventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_239_EventHandler_onLivingSetTarget_LivingSetAttackTargetEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
```

After this the last 6 lines repeat until it crashes.

Mod list: http://pastebin.com/CmVVPkzK

**Comment by BluSunrize** [comment]
I think I've fixed that in coming builds =)
