### ISSUE TITLE
Crash when attacking with Excalibur/Terrasteel sword while Spectral mantle ability is active

### ISSUE THREAD

**Issue by KIdWither** [BluSunrize/WitchingGadgets#58]
~~Using the spectral mantle cape should disable the ability to click(left and right) with items because,~~ When an entity is attacked with the beam (created by left clicking), it crashes. Also the crash bellow does not happen with all mobs.

Also lycanite has a diagnosis for the problem:https://github.com/Lycanite/LycanitesMobs/issues/103#issuecomment-109896787
(original problem before I experimented/tested more)

Versions: 
Botania:1.9.1
Baubles:1.0.1.10
Thuamcraft:4.2.3.5
Travelers Gear:1.16.5
Witching Gadgets:1.1.9

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 6/7/15 11:18 AM
Description: Ticking entity

java.lang.ClassCastException: net.minecraft.entity.passive.EntityBat cannot be cast to net.minecraft.entity.EntityCreature
    at witchinggadgets.common.items.baubles.ItemCloak.onUserTargeted(ItemCloak.java:395)
    at travellersgear.common.util.TGEventHandler.triggerItemEvent(TGEventHandler.java:356)
    at travellersgear.common.util.TGEventHandler.triggerGear(TGEventHandler.java:325)
    at travellersgear.common.util.TGEventHandler.onPlayerTargeted(TGEventHandler.java:198)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_150_TGEventHandler_onPlayerTargeted_LivingSetAttackTargetEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraftforge.common.ForgeHooks.onLivingSetAttackTarget(ForgeHooks.java:282)
    at net.minecraft.entity.EntityLivingBase.func_70604_c(EntityLivingBase.java:379)
    at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:796)
    at net.minecraft.entity.passive.EntityBat.func_70097_a(SourceFile:199)
    at vazkii.botania.common.item.relic.ItemExcaliber.updateBurst(ItemExcaliber.java:202)
    at vazkii.botania.common.entity.EntityManaBurst.func_70071_h_(EntityManaBurst.java:364)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
    at net.minecraft.world.World.func_72870_g(World.java:2034)
    at net.minecraft.world.World.func_72939_s(World.java:1887)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at witchinggadgets.common.items.baubles.ItemCloak.onUserTargeted(ItemCloak.java:395)
    at travellersgear.common.util.TGEventHandler.triggerItemEvent(TGEventHandler.java:356)
    at travellersgear.common.util.TGEventHandler.triggerGear(TGEventHandler.java:325)
    at travellersgear.common.util.TGEventHandler.onPlayerTargeted(TGEventHandler.java:198)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_150_TGEventHandler_onPlayerTargeted_LivingSetAttackTargetEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraftforge.common.ForgeHooks.onLivingSetAttackTarget(ForgeHooks.java:282)
    at net.minecraft.entity.EntityLivingBase.func_70604_c(EntityLivingBase.java:379)
    at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:796)
    at net.minecraft.entity.passive.EntityBat.func_70097_a(SourceFile:199)
    at vazkii.botania.common.item.relic.ItemExcaliber.updateBurst(ItemExcaliber.java:202)
    at vazkii.botania.common.entity.EntityManaBurst.func_70071_h_(EntityManaBurst.java:364)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
    at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
    Entity Type: Botania.botania:manaBurst (vazkii.botania.common.entity.EntityManaBurst)
    Entity ID: 328580
    Entity Name: Mana Burst
    Entity's Exact location: 681.76, 6.32, -414.25
    Entity's Block location: World: (681,6,-415), Chunk: (at 9,0,1 in 42,-26; contains blocks 672,0,-416 to 687,255,-401), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
    Entity's Momentum: 0.65, 0.15, 1.23
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1887)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
    Level name: world for crashes
    All players: 1 total; [EntityPlayerMP['KidWither'/192, l='world for crashes', x=680.86, y=4.50, z=-416.62]]
    Chunk stats: ServerChunkCache: 471 Drop: 0
    Level seed: 2121095848396880586
    Level generator: ID 01 - flat, ver 0. Features enabled: true
    Level generator options: 
    Level spawn location: World: (601,4,-283), Chunk: (at 9,0,5 in 37,-18; contains blocks 592,0,-288 to 607,255,-273), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
    Level time: 5766 game time, 5766 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 77473 (now: false), thunder time: 168942 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Mac OS X (x86_64) version 10.10.3
    Java Version: 1.8.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 228142496 bytes (217 MB) / 480223232 bytes (457 MB) up to 2083782656 bytes (1987 MB)
    JVM Flags: 5 total; -Xmx2000M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 9 mods loaded, 9 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.85.1291} [Forge Mod Loader](forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.2.1291} [Minecraft Forge](forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WitchingGadgetsCore{1.1.9} [Witching Gadgets Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Botania{r1.6-191} [Botania](Botania r1.6-191.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TravellersGear{1.16.5} [Traveller's Gear](TravellersGear-1.7.10-1.16.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WitchingGadgets{1.1.9} [Witching Gadgets](WitchingGadgets-1.7.10-1.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['KidWither'/192, l='world for crashes', x=680.86, y=4.50, z=-416.62]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by BluSunrize** [comment]
I'll look into it

**Comment by KIdWither** [comment]
I did update botania to version 1.9.2 and still get the crash(made sure it still was reproducible with the the latest version of botania).
